# Generated by Django 3.1.2 on 2020-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pthnapp', '0003_auto_20201010_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pthn_unit',
            name='comment_count',
        ),
        migrations.AlterField(
            model_name='pthn_unit',
            name='photo_credit_thumbnail1',
            field=models.CharField(default='?', max_length=50),
        ),
        migrations.AlterField(
            model_name='pthn_unit',
            name='photo_credit_thumbnail2',
            field=models.CharField(default='?', max_length=50),
        ),
        migrations.AlterField(
            model_name='pthn_unit',
            name='photo_credit_thumbnail3',
            field=models.CharField(default='?', max_length=50),
        ),
        migrations.AlterField(
            model_name='pthn_unit',
            name='photo_credit_thumbnailIndex',
            field=models.CharField(default='?', max_length=50),
        ),
    ]
