# Generated by Django 3.1.2 on 2020-10-08 09:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20201008_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='article2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='article3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
