# Generated by Django 3.1.2 on 2020-10-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20201010_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article1',
            new_name='article',
        ),
    ]
