# Generated by Django 3.1.2 on 2020-10-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20201011_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='article1',
        ),
    ]
