# Generated by Django 3.1.2 on 2020-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20201011_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
