# Generated by Django 3.1.2 on 2021-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_auto_20201011_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='image_youtube',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
