# Generated by Django 3.1.2 on 2021-01-27 23:10

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20210127_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_youtube',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default='default.mp3'),
        ),
    ]
