# Generated by Django 3.1.2 on 2021-01-28 01:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_auto_20210127_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
